### ISSUE TITLE
Breaks with modern Ruby

### ISSUE THREAD

**Issue by cabo** [tigris/open-uri-cached#10]
openuri-cached breaks with 

```
lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: URI::HTTPS (Psych::DisallowedClass)
	from /Volumes/nar/Users/cabo-rescue/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'

```

in cached.rb:39:

```
        meta = YAML::load(File.read("#{filename}.meta")) if File.exists?("#{filename}.meta")
```

The problem is this entry in the metadata:

```
:base_uri: !ruby/object:URI::HTTPS
  scheme: https
  user:
```

This is storing the URI object, which doesn't seem to survive YAML and back any more.

I'd store the URI string instead, and convert back upon reading.

**Comment by tigris** [comment]
This seems to work fine on ruby `2.x` as far as I can tell.

I notice a lot more is broken on ruby `3.x` other than just the marshalling of the meta data. I'll look into that, but serializing just the base_uri doesn't feel right, as there may be a lot of other data in the URI object other than just the base_uri.

**Comment by mojavelinux** [comment]
The issue is that Ruby 3.1 has made YAML.load an alias of YAML.safe_load. So it's no longer possible with YAML.load to load a file which contains YAML tags. You can, however, use YAML.unsafe_load, if available to restore the previous behavior.

**Comment by mojavelinux** [comment]
As far as I can tell, this gem works on Ruby 3.1 aside from the YAML.load issue. I have several libraries that have tests that exercise this gem and this is the only problem I've encountered with the functionality.

**Comment by tigris** [comment]
Tests... lol

Yeh, i should write some eh.

**Comment by mojavelinux** [comment]
I could port one of the rspec tests I have so there's at least one in here.

**Comment by mojavelinux** [comment]
To be clear, this doesn't break on Ruby 3.0 unless you have independently upgraded psych. It does break on Ruby 3.1, which ships with psych 4.

> Psych 4.0 changes Psych.load as safe_load by the default. You may need to use Psych 3.3.2 for migrating to this behavior. [Bug #17866]

See https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
