### ISSUE TITLE
Is there a definitive way to "stale" this cache?

### ISSUE THREAD

**Issue by walterdavis** [tigris/open-uri-cached#7]
Without changing the remote URL at all, is there any way to tell open-uri/cached to ignore its local cache and rebuild?

Thanks!

**Comment by tigris** [comment]
Hmm not as such. You *could* `FileUtils.rm_rf OpenURI::Cache.cache_dir` but that's not exactly neat.

**Comment by tigris** [comment]
`OpenURI::Cache.invalidate_all!`
